backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/uploads'

site_url: https://faa.org.mz
logo_url: https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg

show_preview_links: false

collections:
  - label: "Slider"
    name: "slider"
    folder: "collections/_slider"
    create: true
    fields:
      - {label: "Slides", name: "title", default: "Slides", widget: "string"}
      - label: "slide"
        name: "slide"
        widget: "list"
        fields:
          - {label: "Imagem", name: "image", widget: "image"}

  - label: "Perfil"
    name: "perfil"
    folder: "collections/_perfil"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Documento PDF", name: "perfil", widget: "file"}
  
  - label: "Sobre"
    name: "sobre"
    folder: "collections/_sobre"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Objectivos"
    name: "objectivos"
    folder: "collections/_objectivos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown", required: false}

  - label: "Noticias"
    name: "noticias"
    folder: "collections/_posts/noticias"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Categoria", name: "category", default: "noticias", widget: "hidden"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Fotografia", name: "image", widget: "image"}
      - {label: "Artigo", name: "body", widget: "markdown"}

  - label: "Realizações"
    name: "realizacoes"
    folder: "collections/_posts/realizacoes"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Categoria", name: "category", default: "realizacoes", widget: "hidden"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Fotografia", name: "image", widget: "image"}
      - {label: "Artigo", name: "body", widget: "markdown"}

  - label: "Histórias de Sucesso"
    name: "sucessos"
    folder: "collections/_posts/sucessos"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Categoria", name: "category", default: "sucessos", widget: "hidden"}
      - {label: "Projecto e Beneficiario", name: "title", widget: "string"}
      - label: "Beneficiário"
        name: "beneficiary"
        widget: "object"
        fields:
          - {label: "Nome", name: "name", widget: "string"}
          - label: "Fotografias"
            name: "photographies"
            widget: "list"
              - {label: "Fotos", name: "photos", widget: "image"}
          - label: "Ano de Nascimento"
            name: "birthyear"
            widget: "date"
            default: ""
            format: "YYYY"
          - {label: "Ocupação", name: "ocupation", widget: "string"}
          - label: "Povoado"
            name: "village"
            widget: "object"
            fields: 
              - {label: "Povoado", name: "region", widget: "string"}
              - {label: "Localidade", name: "location", widget: "string"}
              - {label: "Distrito", name: "district", widget: "string"}
          - {label: "Filhos", name: "children", widget: "text"}
          - {label: "Área de Trabalho", name: "workingArea", widget: "text"}
          - {label: "Experiência", name: "experience", widget: "text"}
          - {label: "Respectiva", name: "respective", widget: "text"}
          - {label: "Planos para Futuro", name: "futurePlans", widget: "text"}
          - {label: "Desafios", name: "challenges", widget: "text"}
          - {label: "Conselhos", name: "advices", widget: "text"}



  - label: "Projectos"
    name: "projectos"
    folder: "collections/_posts/projectos"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Categoria", name: "category", default: "projectos", widget: "hidden"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Artigo", name: "body", widget: "markdown"}

  - label: "Galeria"
    name: "galeria"
    folder: "collections/_galeria"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}

  - label: "Parceiros"
    name: "parceiros"
    folder: "collections/_parceiros"
    create: true
    fields:
      - {label: "Parceiros", name: "title", default: "Parceiros", widget: "string"}
      - label: "Parceiro"
        name: "parceiro"
        widget: "list"
        fields:
          - {label: "Empresa", name: "company", widget: "string"}
          - {label: "Logotipo", name: "image", widget: "image"}

  - label: "Dados Bancários"
    name: "dbancarios"
    folder: "collections/_dbancarios"
    create: true
    fields:
      - {label: "Nome do Banco", name: "title", widget: "string"}
      - {label: "Número de Conta", name: "number", widget: "number"}
      - {label: "NIB", name: "nib", widget: "number"}
      - {label: "IBAN", name: "nif", widget: "string"}
